"""upd product

Revision ID: 101ec755ca56
Revises: 848e93867460
Create Date: 2024-04-25 11:41:48.064380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "101ec755ca56"
down_revision: Union[str, None] = "848e93867460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("creator_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "creator_type")
    # ### end Alembic commands ###
