"""add discovery-question

Revision ID: 186a23db66da
Revises: fdd3ff0ebd2f
Create Date: 2024-04-25 11:36:58.916616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "186a23db66da"
down_revision: Union[str, None] = "fdd3ff0ebd2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_question",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("bot_transcription", sa.Column("start_time", sa.Float(), nullable=True))
    op.add_column("bot_transcription", sa.Column("end_time", sa.Float(), nullable=True))
    op.add_column("bot_transcription", sa.Column("speaker", sa.String(), nullable=True))
    op.add_column("bot_transcription", sa.Column("text", sa.String(), nullable=True))
    op.add_column("bot_transcription", sa.Column("language", sa.String(), nullable=True))
    op.add_column("bot_transcription", sa.Column("is_final", sa.Boolean(), nullable=True))
    op.drop_column("bot_transcription", "transcript")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_transcription",
        sa.Column(
            "transcript",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("bot_transcription", "is_final")
    op.drop_column("bot_transcription", "language")
    op.drop_column("bot_transcription", "text")
    op.drop_column("bot_transcription", "speaker")
    op.drop_column("bot_transcription", "end_time")
    op.drop_column("bot_transcription", "start_time")
    op.drop_table("discovery_question")
    # ### end Alembic commands ###
