"""upd ask-about

Revision ID: 1f8eade351fd
Revises: a8902d703e5c
Create Date: 2024-05-05 20:24:45.472279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f8eade351fd"
down_revision: Union[str, None] = "a8902d703e5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ask_about", "latency")
    op.drop_column("ask_about", "answer_blob")
    op.drop_column("ask_about", "cost")
    op.drop_column("ask_about", "use_cache")
    op.alter_column("bot_chat", "id", existing_type=sa.BIGINT(), type_=sa.String(), existing_nullable=False)
    op.alter_column("bot_status", "id", existing_type=sa.BIGINT(), type_=sa.String(), existing_nullable=False)
    op.alter_column("bot_transcription", "id", existing_type=sa.BIGINT(), type_=sa.String(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bot_transcription", "id", existing_type=sa.String(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("bot_status", "id", existing_type=sa.String(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("bot_chat", "id", existing_type=sa.String(), type_=sa.BIGINT(), existing_nullable=False)
    op.add_column("ask_about", sa.Column("use_cache", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("ask_about", sa.Column("cost", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column(
        "ask_about",
        sa.Column("answer_blob", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ask_about", sa.Column("latency", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
