"""add ask-about

Revision ID: a8902d703e5c
Revises: 101ec755ca56
Create Date: 2024-05-03 14:54:39.694295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8902d703e5c"
down_revision: Union[str, None] = "101ec755ca56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ask_about",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=True),
        sa.Column("prompt_id", sa.String(), nullable=True),
        sa.Column("org_id", sa.String(), nullable=True),
        sa.Column("org_name", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("creator_type", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("product_name", sa.String(), nullable=True),
        sa.Column("deal_id", sa.String(), nullable=True),
        sa.Column("deal_name", sa.String(), nullable=True),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("follow_up", sa.String(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("inscope", sa.Boolean(), nullable=True),
        sa.Column("intent", sa.String(), nullable=True),
        sa.Column("qa_type", sa.String(), nullable=True),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("source_urns", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_blob", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("video_urn", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_urn", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("roadmap", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fuds", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("knowledge_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answered_from_cache", sa.Boolean(), nullable=True),
        sa.Column("use_cache", sa.Boolean(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ask_about")
    # ### end Alembic commands ###
