"""remove category from discovery

Revision ID: b67640ce6024
Revises: 1f8eade351fd
Create Date: 2024-05-25 21:39:35.197482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b67640ce6024"
down_revision: Union[str, None] = "1f8eade351fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ask_about", sa.Column("output_type", sa.String(), nullable=True))
    op.drop_column("deal_discovery_question", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ask_about", "output_type")
    op.add_column("deal_discovery_question", sa.Column("category", sa.String(), nullable=True))
    # ### end Alembic commands ###
