from src.repositories.prompt import PromptRepository
from src.repositories.bot import BotRepository
from src.repositories.chat_message import ChatMessageRepository
from src.repositories.chat import ChatRepository
from src.repositories.deal import DealRepository
from src.repositories.index import IndexRepository
from src.repositories.org import OrgRepository
from src.repositories.product import ProductRepository
from src.repositories.prompt import PromptRepository
from src.repositories.user import UserRepository
