SYSTEM_MSG = """
## Context:
- You are an AI language model assistant, specialized in document reranking.
- Your task is to classify the given input using the following set of documents and to rerank passages related to a query based on their relevance.

## Instructions:
  *. You must reply with the ID related to the document
  *. Additionally, you need to rerank the provided passages related to a query based on their relevance.
  *. The most relevant passages should be put at the beginning.

## Output format: list[int]
  *. list of ids passages in reranked order, the most relevant at the beginning

## Examples:
---
Beginning Examples
$EXAMPLES
End Examples
---
"""
USER_MSG = "## Input:\nDocuments -> $DOCUMENTS\nQuery -> $QUERY\n## Output:"
EXAMPLE = """
## Input:
Documents ->
ID 1: Marseille is one of the biggest cities in France
ID 2: France is part of Europe
ID 3: The capital of France is Paris
ID 4: France has 60M people
ID 5: Paris is the main city of France
Query -> What is the capital of France?
## Output:
[3, 5, 1, 2, 4]
"""
QUERY = "how enable translation of UI elements?"
DOCS = [
    "QUESTION:\nTranslation/localization support: as a member using my local language, I can easily read instructions and submit feedback in my own local language.\n\nANSWER:\nYes",
    "# Meeting Agenda and Plan\n## Introduction of Team Members\n### Demo and Content Creation Discussion\n#### Replicating Rise 360 User Guide in Gainsight\n\n######################## Vision for Multi-Language Support\nwe covered those languages. No problem. Alright, there we go. Can you see my screen? Alright, nice. Okay, let me start with what vision we have for providing multi-language support on a community. What we aim is to enable our customers to empower their diverse user base by providing an end-to-end localized experience in the user's preferred language or your customer's preferred language in a single instance. Everything that you just saw in the demo that Yori showed you, I'm sure you have seen the destination as well. If a customer of yours from France who prefers French switches to French everything, the vision is that everything inside one single instance will be localized for them. since this is a very huge project and it covers almost every part of the platform, we are taking an iterative approach and today I'll be talking about what we have been working on last couple of months and what's coming up in the short term and then finally what are the plans for the long term. We'll talk broadly about that as well and I can show you as well what progress we have made till now.\n\n######################### Translating UI Elements and Content\nwhat we are working on right now is to translate phrases. Phrases are basically the UI elements text in the UI elements. For example, if you see some text in a button create topic or send or something like that, those are phrases and they can be translated right now to the user's preferred language that the interface, the whole interface of the platform gets translated to a preferred language. How it provides value is right now what you can do with the current capabilities is create either a category within community or knowledge base for a very specific language. For example, Spanish and all the content that is being generated either by the user or by the admins is in Spanish and lives under that category. But as you move to that page, you'll see that all the metadata or the button elements or links, they are in the default language but the content is in Spanish that the experience for the end user is fractured. what we have planned till now, what we have been working on right now would ensure that within an existing language category or a group, we can provide the end user an end-to-end localized experience there at least. And then we can build upon what we have been building till now to add upon all the other facets of the platform.\n\n######################### Transition to Demo\nAre there any questions in the chat?\\nThere are none in the chat, but if anyone would like to ask one, please feel free.\\nFor now, then I'll just show you how it works right now.",
    "QUESTION:\nMulti-translation in apps\n\nANSWER:\nYes, same we have today",
    "QUESTION:\nIs there an option for user to set French as preferred language?\n\nANSWER:\nthere are various ways in which inSided supports multi-language:\n– Create a language category using the community module: https://community.looker.com/ (Japanese Section),\n– Create a language group https://community.c2cglobal.com/ groups (French, German, English)\n– Setup multiple inSided instances, each in their own language https://community.koodomobile.com/ (English) vs. https://communaute.koodomobile.com/ (French)\ninSided doesn't offer an out of the box option to set a preferred language for users. With the help of a custom HTML widget you can create/add a language picker to your platform. This will translate all the platform phrases to a different language. See an example here: https://community.tango.lu/?lang=en",
    "QUESTION:\nWhere to change tool tip for the Back to top button? Currently our tool tip is:“branded.back_to_top”And I would like to translate it in Finnish.\n\nANSWER:\nThis is a phrase you can edit (or create in the first place, if your community doesn’t have it yet).Go to Customization → Phrases → Search for “branded.back_to_top”.If it doesn’t exist:Click “Add phrase”Module: ForumKey: branded.back_to_topSingular: [your phrase]Save changes",
    '# 5 examples of stimulating translations for your community\n\n# 5 examples of stimulating translations for your community\n\n* 4 years ago\n\n 4 March 2019\n* 0 replies\n\n---\n\nThe inSided platform comes with standard text for all buttons and items - however you can change every line of text on your community, so that it fits better your individual need. We recommend you to review these so that you can get the most out of your community.  \n\nWe have collected a number of examples which we think will help your community to perform better after you customize them. Take this as inspiration for further translations on your community!  \n\n**How to change the text of buttons, titles etc. on your community**  \n\nAll of these translations can be changed by using our "Phrases tool". A dedicated how-to can be found here, should you not know how to change them.  \n\nMany phrases can simply be changed by selecting the "Phrases"-button while being logged in:  \n\nHowever some buttons and fields cannot be changed like this. If you cannot click on them, you will need to add them manually in the Control environment [General settings] - [Phrases]). We have included the names of these phrases in our examples, so that you can add them yourself. Should you miss a phrase name, please let us know in the comments!',
    "QUESTION:\nEvents: Timestamp is in English, how to change? Our community is in Finnish and when I create an Event timestamp is in English. I cant find anywhere to change this, is it possible? I mean the Event page and Calendar as well.\n\nANSWER:\nOh, I see.Here’s my theory ️\u200d♀️I think the language of those date &amp; time entriesare tied to your browser language (or the language set as default on your computer).So if yours is set as English, it will be displayed in English.If your users have their computer/browser set on Finnish, they will see it in Finnish too. I’m sure you can test that out.I just changed the language of my browser to German, and the date&amp;timeof our english-speaking community automatically switched to german.This issue occurs in desktop only:In mobile that timestamp is in Finnish.Let me guess, is your cellphone language set to Finnish? ️\u200d♀️Cheers,Daniele",
    '# 5 examples of stimulating translations for your community\n### 1. "Create a topic" / "Ask a question" buttons\n\n**4. Create a topic placeholder text**  \n\nIt can be quite annoying if a user misses to give all the necessary details when asking a question - information like device type, software version or other things might help in providing the correct answer quick. Having a placeholder text in the text field that suggests to add these items will help with that:If you give users an example of items that must be included, you will see that more users will actually follow that advise. Maybe you can even mention that the user will receive a much better, detailed answer. In this example we have added some standard items:  \n\n-*Provide as many details as possible:device name*  \n\n-*software version*  \n\n-*error message (if applicable)*  \n\nIt also is recommended to ask your customers to be specific when it comes to the topic title. Ask them to name the device / issue / question in the title, as this makes it easier for others to find the topic.  \n\nYou can add these directly in the community, but if you would like to add them in the Control environment, you can use the information below:',
    "QUESTION:\nHow can I change the text on the search bar? Hello, I am trying to change the text of the search bar, can someone direct me on how to update this?Thanks!\n\nANSWER:\nJust figured it out!",
    "QUESTION:\nTranslation of information phrase Where can I find this phrase “Enter your username or e-mail address. We'll send you an e-mail with instructions to reset your password.” in the admin panel to translate it into Ukrainian? It is not in the Phrase menu\xa0Thank you\n\nANSWER:\nHi @a.slyusar - yep can you try to add this one:ModuleForumKey:Enter your username or e-mail address. We'll send you an e-mail with instructions to reset your password.Once that’s added you should be able to add a Ukranian version of the phrase - any issues with this please just let us know at support@insided.com:)",
    '# 5 examples of stimulating translations for your community\n### 1. "Create a topic" / "Ask a question" buttons\n\n**Topic title Phrase:**  \n\nModule: Common  \n\nKey:  \n\n*Enter a clear title here*\n**Text box Phrase:**  \n\nModule: Common  \n\nKey: *topic.first.reply.placeholder.textarea*\n**5. Login / Register button**  \n\nBy customizing the login/registration buttons, you can make them more inviting:For these buttons, there are a variety of options to choose from. Try to offer a clear added value that the registration / login will bring.  \n\nFor the **login** button, you could change the text to one of these:  \n\n-Join the discussion  \n\n-Login / Register (for the button on the homepage)  \n\n-Get active  \n\nFor a  \n\n**registration** button, these things could work for you:  \n\n-Register and share your opinion  \n\n-Register and join the discussion  \n\n-Activate your account  \n\nIn the screen below, you can see the various keys for the different Phrases. They are listed as Module|Key. Should you miss one, please let us know!',
    "QUESTION:\nCustomizing Button Title for Community RSVP Is there a way to edit the button title for a community RSVP event? I want to change the name as “ Register for Series” instead of “Attend” ? Attend is the default title. Can someone help?\n\nANSWER:\n@Kamakshi VNice find.. Good self service The exact phrase you need is this:Translation = Text you want.",
    'QUESTION:\nContent Helpfulness: How to modify Hi there, we would like to adapt the Content Helpfulness\xa0bar to include only 2 options (positive / negative)? We would also like to change it to a thumbs up &amp; thumbs down.\xa0\xa0Is it possible in any way, with some CSS or Third Party Script, or other changes?The reason why we would like to change this is that we want to make this score consistent with our other support channels (which have a  voting bar) so we can better compare.\xa0Cheers,Daniele\n\nANSWER:\nfirst thing you would need to do is add custom css to hide the neutral option like so:.qa-topic-neutral-icon{display:none;}to change the images of the happy and sad face you will need use a 3rd party script to change either the SVG image or insert a different image like so://For using an image URLdocument.querySelector(".qa-topic-helpful-icon").innerHTML=\'&lt;img src="thumb up image url here" /&gt;\'document.querySelector(".qa-topic-nothelpful-icon").innerHTML=\'&lt;img src="thumb down image url" /&gt;\'// For using SVGdocument.querySelector(".qa-topic-helpful-icon").innerHTML=\'code for SVG\'document.querySelector(".qa-topic-nothelpful-icon").innerHTML=\'code for SVG\'//example of SVG thumbs updocument.querySelector(".qa-topic-helpful-icon").innerHTML=\'&lt;svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"&gt;&lt;title&gt;ionicons-v5-k&lt;/title&gt;&lt;path d="M456,192,300,180l23-89.4C329,64,322.22,48.73,300.53,42l-34.69-9.85a4,4,0,0,0-4.4,1.72l-129,202.34a8,8,0,0,1-6.81,3.81H16V448H133.61a48,48,0,0,1,15.18,2.46l76.3,25.43a80,80,0,0,0,25.3,4.11H428.32c19,0,31.5-13.52,35.23-32.16L496,305.58V232C496,209.94,478,194,456,192Z"/&gt;&lt;/svg&gt;\'',
    '# 5 examples of stimulating translations for your community\n### 1. "Create a topic" / "Ask a question" buttons\n\n### 1. "Create a topic" / "Ask a question" buttons\n\nThese are the buttons you want your users to click on. So make sure that they are inviting and customized to fit the goal of your community.There are several buttons which invite users to start a new discussion, so there are also several phrases for this.  \n\nShould you want to add the phrase manually, here are the details:  \n\nModule: Forum  \n\nKey:  \n\n*branded.cta.intro.second*  \n\nAnother button is the "Create topic" button in the header.  \n\nModule: Forum  \n\nKey: *branded.cta.intro.second*',
    '# 5 examples of stimulating translations for your community\n\n### A few extra suggestions for improvements:\n\n* Notification emails (check this topic for more inspiration)   \n* Widget text / Badge activity can be changed in the widget settings (e.g. "most awesome" / "Community heroes" / "Hall of fame")\n\n---',
    "QUESTION:\nCustomizing Embeddable widget How can I customize the text 'help' of the Floathing button?\n\nANSWER:\nHi!This is a quick change that you can do fairly easily. Simply head into Control &gt; Integrations &gt; Embeddable Widget Customization and then edit Trigger Settings &gt; Trigger Text to your liking, such as Need more help?or anything else of your choice. Don’t forget to save!If you’re looking for more options, there’s also an article that goes into more detail.",
    '# 5 examples of stimulating translations for your community\n### 1. "Create a topic" / "Ask a question" buttons\n\n**2. Call to action intros**  \n\nThe "Call to action intros" are the three points which are being displayed to every (new) user to the community. They are very visible and a good spot to stimulate your users to become active themselves:  \n\nIf you do not see this on your community, you probably have closed this (by clicking on the x). As you cannot bring it back (it is mainly targeted at new visitors), you might have to change it via the Phrases tool.  \n\nAs there are three items, there are three different phrases for it:  \n\nModule: Forum  \n\nKey:  \n\n*branded.cta.intro.first*  \n\nModule: Forum  \n\nKey:  \n\n*branded.cta.intro.second*  \n\nModule: Forum  \n\nKey: *branded.cta.intro.third*',
    '# 5 examples of stimulating translations for your community\n### 1. "Create a topic" / "Ask a question" buttons\n\n**3. Placeholder in the search bar**  \n\nThe search bar has a very prominent position in your community. Nevertheless we see that not many visitors are making use of this feature (which is a common issue in online communities). To prevent users from asking question that already exist, it is a good idea to improve the placeholder text in the search bar with something stimulating.Instead of just saying "Search", you can put much more inspiring / activating text in this bar.  \n\nSome suggestions:  \n* Find your answer   \n* Search our community   \n* Search our Knowledgebase   \n* Start typing to see suggested answers\n\nThis piece of text can be edited by adding the following phrase:  \n\nModule: ForumKey:*live.search.placeholder*',
    '# How To Change The Text Of Links, Buttons, And Labels (Phrases)\n\n# How To Change The Text Of Links, Buttons, And Labels (Phrases)\n\n* 6 years ago\n\n11 January 2018\n* 29 replies\n\n---\n\nDo the links, buttons and labels on your community not match your branding? Use our ‘Phrases’ tool to change certain text into something that resonates.\xa0\n\nA phrase is customizable text on your community platform. For example, if you wanted to change the “Log in” button to say “Lets go!” you would be changing the phrase. All phrases have a default setting, but almost all language on the platform can be changed.\xa0\n\nUsually, you can change text strings right on the community with our live edit too; however, some phrases need to be changed manually on the back end. For this, you can reference the articles below:\n\nHidden Phrases: (Insided Standard) Login/Registration Page\n\nHow to Customize your Error Pages\n\nHidden Phrases: Change text on the "set username" page (SSO registration)\n\n## How To Change The Text Of Links, Buttons, And Labels (Phrases)\n\n* Log into\xa0the Community Frontend (not control)\n* Switch on the ‘**Phrases**’ **toggle** at the bottom-right hand corner of the screen.\n\n* All editable phrases will be indicated with an ‘edit’ label.\n\n* **Click** the element/text you want to change. An input field will appear at the top of your screen.\n* Add in your new text, and click **Save** - your change is now saved as a new ‘Phrase’.\n\nSwitch off the ‘**Phrases**’ **toggle** and **Double-check** the phrase on the community. Does everything look good?\xa0  \n\n> *Currently, only users with the ‘Admin’ role can use this tool.* You can view and search through all of your custom phrases by going to Control → Customization → Phrases.  \n>   \n>  Some of our craftier customers worked out how to use the phrase tool to create rich email notifications. Interested? Read (unofficial) How To Use The Phrase Tool To Create Rich Email Notifications. Sometimes, our customers generously dedicate their time to write these guides, enabling me to kick back and take some me-time! .\n\n---',
    "Optimize pages for search\n \n(Sub)domain support\nOptimized header and page structure semantics within community templates for \noptimal page crawling and ranking results\nAbility to support custom (sub)domains within the client to host entire platform on\n \nModification & branding features\nWhile you don’t want to pay through the nose for an entirely custom-built community platform, you still need \nto have some decent control over the look and feel of your community and make sure it sits in line with your \nbrand guidelines. After all, this should be a seamless user experience for your customers, so take the time \nwhen assessing vendors to pick a platform that gives you the flexibility and modification you need—no \ndevelopers required.\nCommunity branding\n \nChange layout\nCommunity branding\nEasily change community branding (colors, button style, images, icons) from console, \nwithout any programming needed\nChange layout of home page and category pages from console without \nprogramming\nThe Community Platform Comparison Guide 16",
]
